export const CATEGORIES = [
  { id: '1', label: 'Dogs', icon: '🐕' },
  { id: '2', label: 'Cats', icon: '🐈' },
  { id: '3', label: 'Birds', icon: '🦜' },
  { id: '4', label: 'Exotic Pets', icon: '🦎' },
  { id: '5', label: 'Training', icon: '🎯' },
  { id: '6', label: 'Health', icon: '🩺' },
];

export const COMMUNITIES = [
  {
    id: '1',
    name: 'German Shepherd Owners',
    members: 12480,
    description: 'A loving community for GSD parents sharing tips, stories, and advice.',
    category: 'Dogs',
    image: 'https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?w=400&q=80',
    joined: false,
  },
  {
    id: '2',
    name: 'Golden Retriever Lovers',
    members: 18920,
    description: 'Everything about the most gentle and loving breed in the world.',
    category: 'Dogs',
    image: 'https://images.unsplash.com/photo-1633722715463-d30f4f325e24?w=400&q=80',
    joined: true,
  },
  {
    id: '3',
    name: 'Persian Cat Community',
    members: 9340,
    description: 'Dedicated to the elegance and care of Persian cats worldwide.',
    category: 'Cats',
    image: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=400&q=80',
    joined: false,
  },
  {
    id: '4',
    name: 'Parrot & Bird Parents',
    members: 5210,
    description: "Share your feathered friends' moments and care knowledge.",
    category: 'Birds',
    image: 'https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=400&q=80',
    joined: false,
  },
  {
    id: '5',
    name: 'Exotic Pet Keepers',
    members: 3780,
    description: 'For owners of reptiles, amphibians, and other exotic companions.',
    category: 'Exotic Pets',
    image: 'https://images.unsplash.com/photo-1504450874802-0ba2bcd9b5ae?w=400&q=80',
    joined: false,
  },
  {
    id: '6',
    name: 'Pet Health & Wellness',
    members: 22100,
    description: "Expert tips and community support for your pet's health journey.",
    category: 'Health',
    image: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=400&q=80',
    joined: true,
  },
];

export const POSTS = [
  {
    id: '1',
    userId: 'u1',
    userName: 'Priya Sharma',
    petName: 'Bruno',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&q=80',
    avatarInitials: 'PS',
    community: 'German Shepherd Owners',
    communityId: '1',
    text: 'Bruno just turned 2 today! 🎉 He has grown so much and I couldn\'t be more proud. From a tiny pup to this majestic boy — thank you all for the training tips along the way!',
    image: null,
    hasImage: false,
    likes: 148,
    comments: 34,
    shares: 12,
    time: '2 hours ago',
    liked: false,
    isAdmin: true,
  },
  {
    id: '2',
    userId: 'u2',
    userName: 'Arjun Mehta',
    petName: 'Mango',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&q=80',
    avatarInitials: 'AM',
    community: 'Golden Retriever Lovers',
    communityId: '2',
    text: 'Quick question for the community — is it normal for Goldens to shed THIS much in summer? Mango seems to be leaving fur everywhere 😅 Any grooming tips would be super helpful!',
    image: null,
    hasImage: false,
    likes: 89,
    comments: 52,
    shares: 6,
    time: '5 hours ago',
    liked: true,
    isAdmin: false,
  },
  {
    id: '3',
    userId: 'u3',
    userName: 'Sneha Kapoor',
    petName: 'Whiskers',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&q=80',
    avatarInitials: 'SK',
    community: 'Persian Cat Community',
    communityId: '3',
    text: 'My Persian baby Whiskers had her first vet checkup and got a clean bill of health! The vet was amazed at how calm she stayed. So proud of her 🐱✨',
    image: null,
    hasImage: false,
    likes: 203,
    comments: 41,
    shares: 19,
    time: '1 day ago',
    liked: false,
    isAdmin: false,
  },
  {
    id: '4',
    userId: 'u4',
    userName: 'Rohan Das',
    petName: 'Rocky',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&q=80',
    avatarInitials: 'RD',
    community: 'Pet Health & Wellness',
    communityId: '6',
    text: 'Important reminder: Summer heat can be dangerous for pets! 🌞 Make sure your furry friends have fresh water at all times, avoid walks during peak hours (12–4 PM), and never leave them in parked cars.',
    image: null,
    hasImage: false,
    likes: 412,
    comments: 67,
    shares: 88,
    time: '2 days ago',
    liked: true,
    isAdmin: false,
  },
];

export const COMMUNITY_POSTS = {
  '1': [
    {
      id: 'cp1',
      userId: 'u5',
      userName: 'Kavita Nair',
      petName: 'Bolt',
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&q=80',
      avatarInitials: 'KN',
      community: 'German Shepherd Owners',
      text: 'Best breed for apartment living? My GSD loves it but neighbours complain about the barking 😅',
      hasImage: false,
      likes: 32,
      comments: 14,
      shares: 2,
      time: '3 hours ago',
      liked: false,
      isAdmin: false,
    },
  ],
  '2': [],
  '6': [],
};
