export const SERVICE_ICONS = {
  Grooming:    { name: 'content-cut',       color: '#7B5EA7' },
  'Vet Visit': { name: 'stethoscope',        color: '#1976D2' },
  Training:    { name: 'school-outline',     color: '#E65100' },
  Vaccination: { name: 'needle',             color: '#C62828' },
  Daycare:     { name: 'home-heart',         color: '#00838F' },
  Hostel:      { name: 'bed-outline',        color: '#558B2F' },
};

export const ORDERS_DATA = [
  {
    id: 'VET-2024-001',
    service: 'Pet Grooming',
    serviceType: 'Grooming',
    pet: { name: 'Rocky', breed: 'Golden Retriever', age: '3 yrs' },
    date: '12 March, 2024',
    time: '11:00 AM',
    price: 799,
    currency: '₹',
    status: 'Completed',
    location: 'Home Visit',
    address: 'Sector 12, Dwarka, New Delhi',
    professional: { name: 'Ananya Sharma', role: 'Certified Groomer' },
    payment: { method: 'UPI', amount: 799, status: 'Paid' },
    notes: 'Full grooming — bath, trimming, nail clipping',
  },
  {
    id: 'VET-2024-002',
    service: 'Vet Consultation',
    serviceType: 'Vet Visit',
    pet: { name: 'Luna', breed: 'Persian Cat', age: '2 yrs' },
    date: '18 March, 2024',
    time: '2:30 PM',
    price: 499,
    currency: '₹',
    status: 'Active',
    location: 'Clinic',
    address: 'Vetician Clinic, Lajpat Nagar, New Delhi',
    professional: { name: 'Dr. Rajesh Mehta', role: 'Veterinarian' },
    payment: { method: 'Card', amount: 499, status: 'Paid' },
    notes: 'Routine health check-up and deworming',
  },
  {
    id: 'VET-2024-003',
    service: 'Dog Training',
    serviceType: 'Training',
    pet: { name: 'Bruno', breed: 'German Shepherd', age: '1 yr' },
    date: '5 March, 2024',
    time: '9:00 AM',
    price: 1299,
    currency: '₹',
    status: 'Completed',
    location: 'Home Visit',
    address: 'Sector 18, Noida, UP',
    professional: { name: 'Kiran Patel', role: 'Dog Trainer' },
    payment: { method: 'UPI', amount: 1299, status: 'Paid' },
    notes: 'Basic obedience training — 2 hr session',
  },
  {
    id: 'VET-2024-004',
    service: 'Pet Vaccination',
    serviceType: 'Vaccination',
    pet: { name: 'Coco', breed: 'Beagle', age: '6 months' },
    date: '22 March, 2024',
    time: '4:00 PM',
    price: 899,
    currency: '₹',
    status: 'Cancelled',
    location: 'Clinic',
    address: 'Vetician Clinic, Lajpat Nagar, New Delhi',
    professional: { name: 'Dr. Priya Singh', role: 'Veterinarian' },
    payment: { method: 'UPI', amount: 899, status: 'Refunded' },
    notes: 'Annual booster vaccination package',
  },
  {
    id: 'VET-2024-005',
    service: 'Daycare',
    serviceType: 'Daycare',
    pet: { name: 'Rocky', breed: 'Golden Retriever', age: '3 yrs' },
    date: '28 March, 2024',
    time: '8:00 AM',
    price: 349,
    currency: '₹',
    status: 'Active',
    location: 'Center',
    address: 'Vetician Daycare, Vasant Kunj, New Delhi',
    professional: { name: 'Vetician Daycare Team', role: 'Care Staff' },
    payment: { method: 'UPI', amount: 349, status: 'Paid' },
    notes: 'Full day care with play, meals and nap time',
  },
  {
    id: 'VET-2024-006',
    service: 'Pet Hostel',
    serviceType: 'Hostel',
    pet: { name: 'Luna', breed: 'Persian Cat', age: '2 yrs' },
    date: '1 April, 2024',
    time: '10:00 AM',
    price: 1199,
    currency: '₹',
    status: 'Active',
    location: 'Center',
    address: 'Vetician Pet Hostel, Greater Kailash, New Delhi',
    professional: { name: 'Vetician Hostel Team', role: 'Care Staff' },
    payment: { method: 'Card', amount: 1199, status: 'Paid' },
    notes: '3-night stay with premium care and meals',
  },
];

export const FILTER_TABS = ['All', 'Active', 'Completed', 'Cancelled'];
