export const FAVORITE_VETS = [
  {
    id: '1',
    name: 'Dr. Priya Sharma',
    specialization: 'Small Animal Surgery',
    clinic: 'PawCare Clinic',
    location: 'Koramangala',
    address: '14/3, 5th Block, Koramangala, Bengaluru 560034',
    phone: '+919876543210',
    rating: 4.9,
    distance: '1.2 km',
    experience: '12 yrs',
    fee: '₹600',
    available: true,
    image: 'https://images.pexels.com/photos/5452201/pexels-photo-5452201.jpeg?auto=compress&cs=tinysrgb&w=200',
    initials: 'PS',
    services: ['Surgeries', 'X-Ray', 'Vaccinations', 'Dental', 'Emergency'],
    timings: [
      { day: 'Mon–Fri', hours: '9:00 AM – 6:00 PM', closed: false },
      { day: 'Saturday', hours: '9:00 AM – 2:00 PM', closed: false },
      { day: 'Sunday', hours: 'Closed', closed: true },
    ],
  },
  {
    id: '2',
    name: 'Dr. Rajan Mehta',
    specialization: 'Veterinary Dermatology',
    clinic: 'Fur & Feathers',
    location: 'Indiranagar',
    address: '22, 100 Feet Road, Indiranagar, Bengaluru 560038',
    phone: '+918765432109',
    rating: 4.7,
    distance: '2.4 km',
    experience: '8 yrs',
    fee: '₹800',
    available: true,
    image: 'https://images.pexels.com/photos/5215024/pexels-photo-5215024.jpeg?auto=compress&cs=tinysrgb&w=200',
    initials: 'RM',
    services: ['Skin Allergy', 'Dermatology', 'Grooming', 'Blood Test'],
    timings: [
      { day: 'Mon–Wed', hours: '10:00 AM – 7:00 PM', closed: false },
      { day: 'Thu–Sat', hours: '11:00 AM – 5:00 PM', closed: false },
      { day: 'Sunday', hours: 'Closed', closed: true },
    ],
  },
  {
    id: '3',
    name: 'Dr. Ananya Nair',
    specialization: 'Exotic Animal Care',
    clinic: 'ZooVet Hospital',
    location: 'HSR Layout',
    address: '8th Sector, HSR Layout, Bengaluru 560102',
    phone: '+917654321098',
    rating: 4.8,
    distance: '3.1 km',
    experience: '10 yrs',
    fee: '₹950',
    available: false,
    image: 'https://images.pexels.com/photos/5407206/pexels-photo-5407206.jpeg?auto=compress&cs=tinysrgb&w=200',
    initials: 'AN',
    services: ['Birds', 'Reptiles', 'Rabbits', 'Exotic Pets', 'Diagnostics'],
    timings: [
      { day: 'Tue–Sat', hours: '10:00 AM – 4:00 PM', closed: false },
      { day: 'Monday', hours: 'By Appointment', closed: false },
      { day: 'Sunday', hours: 'Closed', closed: true },
    ],
  },
  {
    id: '4',
    name: 'Dr. Vikram Iyer',
    specialization: 'General Veterinary',
    clinic: 'PetLife Wellness',
    location: 'JP Nagar',
    address: '3rd Phase, JP Nagar, Bengaluru 560078',
    phone: '+916543210987',
    rating: 4.6,
    distance: '4.0 km',
    experience: '6 yrs',
    fee: '₹400',
    available: true,
    image: 'https://images.pexels.com/photos/4173251/pexels-photo-4173251.jpeg?auto=compress&cs=tinysrgb&w=200',
    initials: 'VI',
    services: ['Checkups', 'Vaccinations', 'Deworming', 'Nutrition Advice'],
    timings: [
      { day: 'Mon–Sat', hours: '8:00 AM – 8:00 PM', closed: false },
      { day: 'Sunday', hours: '10:00 AM – 2:00 PM', closed: false },
    ],
  },
];

export const RECOMMENDED_VETS = [
  {
    id: 'r1',
    name: 'Dr. Kavya Reddy',
    specialization: 'Ophthalmology',
    clinic: 'ClearEye Pet Clinic',
    location: 'Whitefield',
    address: '12, ITPL Road, Whitefield, Bengaluru 560066',
    phone: '+915543210987',
    rating: 4.9,
    distance: '5.2 km',
    experience: '9 yrs',
    fee: '₹750',
    available: true,
    image: 'https://images.pexels.com/photos/5452293/pexels-photo-5452293.jpeg?auto=compress&cs=tinysrgb&w=200',
    initials: 'KR',
    services: ['Eye Checkup', 'Cataract', 'Glaucoma', 'Eye Surgery'],
    timings: [
      { day: 'Mon–Fri', hours: '9:00 AM – 5:00 PM', closed: false },
      { day: 'Saturday', hours: '10:00 AM – 1:00 PM', closed: false },
      { day: 'Sunday', hours: 'Closed', closed: true },
    ],
  },
  {
    id: 'r2',
    name: 'Dr. Arjun Das',
    specialization: 'Orthopaedics',
    clinic: 'BoneCare Vet',
    location: 'Marathahalli',
    address: '7, Outer Ring Road, Marathahalli, Bengaluru 560037',
    phone: '+914432109876',
    rating: 4.8,
    distance: '6.1 km',
    experience: '11 yrs',
    fee: '₹1100',
    available: true,
    image: 'https://images.pexels.com/photos/4225880/pexels-photo-4225880.jpeg?auto=compress&cs=tinysrgb&w=200',
    initials: 'AD',
    services: ['Fractures', 'Joint Surgery', 'Physiotherapy', 'X-Ray'],
    timings: [
      { day: 'Mon–Sat', hours: '10:00 AM – 6:00 PM', closed: false },
      { day: 'Sunday', hours: 'Closed', closed: true },
    ],
  },
  {
    id: 'r3',
    name: 'Dr. Meena Pillai',
    specialization: 'Dentistry',
    clinic: 'SmilePet Dental',
    location: 'Jayanagar',
    address: '4th T Block, Jayanagar, Bengaluru 560041',
    phone: '+913321098765',
    rating: 4.7,
    distance: '2.8 km',
    experience: '7 yrs',
    fee: '₹650',
    available: false,
    image: 'https://images.pexels.com/photos/5214958/pexels-photo-5214958.jpeg?auto=compress&cs=tinysrgb&w=200',
    initials: 'MP',
    services: ['Teeth Cleaning', 'Extraction', 'Dental X-Ray', 'Oral Surgery'],
    timings: [
      { day: 'Tue–Sat', hours: '11:00 AM – 6:00 PM', closed: false },
      { day: 'Mon & Sun', hours: 'Closed', closed: true },
    ],
  },
];
