export const CATEGORIES = [
  { id: 'all', label: 'All', icon: 'paw' },
  { id: 'nutrition', label: 'Nutrition', icon: 'food-apple' },
  { id: 'grooming', label: 'Grooming', icon: 'scissors-cutting' },
  { id: 'training', label: 'Training', icon: 'school' },
  { id: 'health', label: 'Health', icon: 'heart-pulse' },
  { id: 'behavior', label: 'Behavior', icon: 'brain' },
  { id: 'emergency', label: 'Emergency', icon: 'ambulance' },
];

export const TIPS_DATA = [
  {
    id: '1',
    title: '5 Essential Grooming Tips for Dogs',
    shortDescription: 'Keep your dog clean, healthy, and happy with these expert-approved grooming practices.',
    category: 'grooming',
    readTime: '3 min read',
    isFeatured: true,
    image: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=800&q=80',
    vetName: 'Dr. Sarah Mitchell',
    vetTitle: 'Certified Veterinary Dermatologist',
    content: `Regular grooming is one of the most important aspects of pet care. It not only keeps your dog looking great but also plays a vital role in their overall health and wellbeing.

Grooming sessions are also a wonderful opportunity to bond with your pet and check for any unusual lumps, bumps, or skin issues that might need veterinary attention.`,
    bulletPoints: [
      'Brush your dog\'s coat at least 2–3 times per week to prevent matting and reduce shedding.',
      'Bathe your dog every 4–6 weeks using a pH-balanced, dog-specific shampoo.',
      'Trim nails every 3–4 weeks — overgrown nails can cause discomfort and joint issues.',
      'Clean ears weekly with a vet-approved solution to prevent infections.',
      'Brush teeth daily or at least 3 times a week to prevent dental disease.',
    ],
    vetAdvice: 'Regular grooming not only maintains hygiene but also helps detect early signs of skin conditions, parasites, or infections. I recommend establishing a grooming routine from puppyhood so your pet grows comfortable with the process.',
    helpfulCount: 142,
    savedCount: 87,
  },
  {
    id: '2',
    title: 'Healthy Diet for Puppies',
    shortDescription: 'Everything you need to know about feeding your puppy the right nutrients for healthy growth.',
    category: 'nutrition',
    readTime: '2 min read',
    isFeatured: false,
    image: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=800&q=80',
    vetName: 'Dr. James Chen',
    vetTitle: 'Board-Certified Veterinary Nutritionist',
    content: `Puppies have very different nutritional needs compared to adult dogs. They are growing rapidly and require a diet that supports bone development, muscle growth, and immune system strength.

Choosing the right food during this critical period sets the foundation for lifelong health. Always look for foods formulated specifically for puppies or "all life stages."`,
    bulletPoints: [
      'Feed puppies 3–4 small meals per day until 6 months old, then transition to twice daily.',
      'Choose food with real meat (chicken, beef, or fish) listed as the first ingredient.',
      'Ensure the food meets AAFCO nutritional standards for growth.',
      'Avoid giving table scraps, especially toxic foods like grapes, onions, and chocolate.',
      'Always provide fresh, clean water — hydration is as important as nutrition.',
    ],
    vetAdvice: 'I always advise pet parents to consult a vet before switching food brands. A gradual transition over 7–10 days prevents digestive upset. If your puppy shows signs of food sensitivity like vomiting or diarrhea, seek veterinary advice promptly.',
    helpfulCount: 98,
    savedCount: 64,
  },
  {
    id: '3',
    title: 'Basic Training Commands Every Dog Should Know',
    shortDescription: 'Start with these 6 foundational commands to build a well-behaved, confident dog.',
    category: 'training',
    readTime: '4 min read',
    isFeatured: false,
    image: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=800&q=80',
    vetName: 'Dr. Priya Sharma',
    vetTitle: 'Animal Behaviorist & Trainer',
    content: `Training your dog is one of the most rewarding experiences of pet ownership. It builds trust, strengthens your bond, and ensures your dog's safety in various situations.

Positive reinforcement is scientifically proven to be the most effective and humane training method. Reward good behavior immediately with treats, praise, or play.`,
    bulletPoints: [
      '"Sit" — The foundational command. Hold a treat above your dog\'s nose and slowly move it back.',
      '"Stay" — Build duration gradually. Start with 2 seconds and increase over sessions.',
      '"Come" — Life-saving recall command. Always reward generously when your dog comes to you.',
      '"Down" — Helps manage excitement. Lure the dog into position with a treat.',
      '"Leave it" — Prevents dangerous item consumption. Practice with low-value items first.',
      '"Heel" — Teaches leash manners and builds focus during walks.',
    ],
    vetAdvice: 'Keep training sessions short — 5 to 10 minutes — and end on a positive note. Consistency is key: use the same words and hand signals every time. Avoid punishment-based training as it can cause anxiety and aggression.',
    helpfulCount: 215,
    savedCount: 130,
  },
  {
    id: '4',
    title: 'Signs Your Cat Might Be Sick',
    shortDescription: 'Cats are masters at hiding illness. Learn the subtle signs that your feline needs a vet visit.',
    category: 'health',
    readTime: '3 min read',
    isFeatured: false,
    image: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=800&q=80',
    vetName: 'Dr. Amanda Torres',
    vetTitle: 'Feline Medicine Specialist',
    content: `Cats are instinctively programmed to hide signs of illness — a survival mechanism from their wild ancestors. This makes it challenging for pet parents to know when their cat needs medical attention.

Regular health monitoring and knowing your cat's normal behavior patterns are your best tools for early detection.`,
    bulletPoints: [
      'Changes in eating or drinking habits — eating less or drinking much more than usual.',
      'Hiding more than normal or avoiding human contact.',
      'Changes in litter box usage — frequency, consistency, or blood in urine/stool.',
      'Sudden weight loss or gain over a short period.',
      'Excessive grooming or, conversely, a dull, unkempt coat.',
      'Labored breathing, coughing, or sneezing repeatedly.',
    ],
    vetAdvice: 'Cats should have wellness exams at least once a year, and twice yearly for senior cats over 7. Early detection of conditions like kidney disease, diabetes, and hyperthyroidism significantly improves outcomes and quality of life.',
    helpfulCount: 178,
    savedCount: 112,
  },
  {
    id: '5',
    title: 'Understanding Dog Body Language',
    shortDescription: 'Learn to read your dog\'s emotions and communicate more effectively with your furry friend.',
    category: 'behavior',
    readTime: '5 min read',
    isFeatured: false,
    image: 'https://images.unsplash.com/photo-1561037404-61cd46aa615b?w=800&q=80',
    vetName: 'Dr. Michael Osei',
    vetTitle: 'Veterinary Behaviorist',
    content: `Understanding what your dog is communicating through body language is fundamental to a healthy relationship. Dogs are constantly "talking" to us — we just need to learn their language.

Misreading body language can lead to bites, anxiety, and a breakdown of trust. This guide will help you decode the most common signals.`,
    bulletPoints: [
      'A relaxed, wagging tail at mid-height indicates a happy, confident dog.',
      'Tail tucked between legs signals fear, anxiety, or submission.',
      'Yawning in non-tired situations is a calming signal — the dog is stressed.',
      'Whale eye (showing whites of eyes) is a warning sign of discomfort.',
      'Play bow (front down, rear up) is a clear invitation to play.',
      'Stiff body, raised hackles, and a fixed stare signal potential aggression.',
    ],
    vetAdvice: 'Never punish a dog for growling — it is their warning system. Remove them from stressful situations instead. A dog that cannot communicate discomfort may escalate to biting without warning. Always respect their boundaries.',
    helpfulCount: 203,
    savedCount: 145,
  },
  {
    id: '6',
    title: 'Pet First Aid: What Every Owner Must Know',
    shortDescription: 'Be prepared for emergencies with these essential first-aid techniques for pets.',
    category: 'emergency',
    readTime: '6 min read',
    isFeatured: false,
    image: 'https://images.unsplash.com/photo-1601758124510-52d02ddb7cbd?w=800&q=80',
    vetName: 'Dr. Lisa Park',
    vetTitle: 'Emergency & Critical Care Veterinarian',
    content: `Emergencies can happen at any time. Knowing basic pet first aid can be the difference between life and death while you transport your pet to an emergency vet clinic.

Remember: first aid is not a substitute for veterinary care. Always contact your vet or an emergency animal hospital immediately after providing first aid.`,
    bulletPoints: [
      'Keep an emergency vet number saved in your phone at all times.',
      'For bleeding wounds, apply firm pressure with a clean cloth for 5 minutes.',
      'If your pet is choking, look inside the mouth and remove visible obstructions carefully.',
      'For suspected poisoning, call the ASPCA Animal Poison Control Center immediately.',
      'Do not give human medications to pets without vet guidance — many are toxic.',
      'Know the signs of heatstroke: excessive panting, drooling, and weakness — cool with water and rush to a vet.',
    ],
    vetAdvice: 'I strongly recommend taking a pet first aid course. Having a home first aid kit with gauze, antiseptic, a digital thermometer, and your vet\'s contact information can save precious time in an emergency.',
    helpfulCount: 267,
    savedCount: 198,
  },
];
