// data/mockNotifications.js

export const NOTIFICATION_TYPES = {
  GROOMING: 'grooming',
  VET: 'vet',
  HOSTEL: 'hostel',
  TRAINING: 'training',
  DAYCARE: 'daycare',
  VACCINATION: 'vaccination',
  ORDER: 'order',
  PAYMENT: 'payment',
  WATCHING: 'watching',
};

export const mockNotifications = [
  {
    id: '1',
    title: 'Grooming Appointment Confirmed',
    description: "Your grooming session for Rocky is scheduled for tomorrow at 10 AM. Please make sure Rocky has had a light meal before arrival.",
    type: NOTIFICATION_TYPES.GROOMING,
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    isRead: false,
    petName: 'Rocky',
    actionRoute: '/grooming/details',
    extraDetails: {
      appointmentDate: 'Tomorrow, 10:00 AM',
      location: 'Vetician Grooming Hub, Sector 5',
      groomer: 'Priya Sharma',
      services: ['Bath & Blow Dry', 'Nail Trim', 'Ear Cleaning'],
      duration: '1.5 hours',
      price: '₹850',
    },
  },
  {
    id: '2',
    title: 'Vet Consultation Reminder',
    description: "Dr. Mehta is ready for Bruno's consultation at 3 PM today. Don't forget to carry previous reports.",
    type: NOTIFICATION_TYPES.VET,
    timestamp: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    isRead: false,
    petName: 'Bruno',
    actionRoute: '/vet/consultation',
    extraDetails: {
      appointmentDate: 'Today, 3:00 PM',
      doctor: 'Dr. Rajeev Mehta (BVSc)',
      clinic: 'Vetician Clinic, MG Road',
      purpose: 'General Health Checkup',
      notes: 'Carry last 3 months vaccination records',
      consultationFee: '₹500',
    },
  },
  {
    id: '3',
    title: 'Pet Hostel Check-in Confirmed',
    description: "Bella's 3-night stay at Vetician Hostel starts Dec 22. Room 4B is ready with all premium amenities.",
    type: NOTIFICATION_TYPES.HOSTEL,
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    isRead: true,
    petName: 'Bella',
    actionRoute: '/hostel/details',
    extraDetails: {
      checkIn: 'Dec 22, 11:00 AM',
      checkOut: 'Dec 25, 11:00 AM',
      room: 'Room 4B – Premium Suite',
      amenities: ['Daily Walks', '24/7 Care', 'Webcam Access', 'Gourmet Meals'],
      totalCost: '₹3,600',
      caretaker: 'Ankit Verma',
    },
  },
  {
    id: '4',
    title: 'Training Session Completed',
    description: "Max completed Week 3 of Basic Obedience Training. Trainer Arjun gave him 4.8/5 stars this week!",
    type: NOTIFICATION_TYPES.TRAINING,
    timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    isRead: true,
    petName: 'Max',
    actionRoute: '/training/progress',
    extraDetails: {
      sessionDate: 'Yesterday, 5:00 PM',
      trainer: 'Arjun Kapoor (Certified K9 Trainer)',
      week: 'Week 3 of 8',
      rating: '4.8 / 5',
      skillsLearned: ['Sit & Stay', 'Leash Walking', 'Recall Command'],
      nextSession: 'Dec 24, 5:00 PM',
    },
  },
  {
    id: '5',
    title: 'Vaccination Due Tomorrow',
    description: "Charlie's annual Rabies + DHPP booster is due tomorrow. Book your slot now to avoid rescheduling.",
    type: NOTIFICATION_TYPES.VACCINATION,
    timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    isRead: false,
    petName: 'Charlie',
    actionRoute: '/vaccination/book',
    extraDetails: {
      dueDate: 'Tomorrow',
      vaccines: ['Rabies Booster', 'DHPP Combo', 'Leptospirosis'],
      clinic: 'Vetician Vaccination Center',
      estimatedCost: '₹1,200',
      lastVaccination: 'Dec 18, 2023',
      doctor: 'Dr. Sunita Rao',
    },
  },
  {
    id: '6',
    title: 'Payment Successful',
    description: "₹1,250 paid successfully for Luna's Daycare (Dec 20–21). Your receipt has been emailed to you.",
    type: NOTIFICATION_TYPES.PAYMENT,
    timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    isRead: true,
    petName: 'Luna',
    actionRoute: '/orders/receipt',
    extraDetails: {
      transactionId: 'VTC-2024-00892',
      amount: '₹1,250',
      paymentMethod: 'UPI – PhonePe',
      service: 'Daycare (2 Days)',
      paidOn: 'Dec 20, 2024 – 9:14 AM',
      status: 'Successful',
    },
  },
  {
    id: '7',
    title: 'Daycare Drop-off Reminder',
    description: "Luna's daycare starts at 8 AM tomorrow. Our team will welcome her at the Vetician Daycare entrance.",
    type: NOTIFICATION_TYPES.DAYCARE,
    timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    isRead: false,
    petName: 'Luna',
    actionRoute: '/daycare/details',
    extraDetails: {
      date: 'Tomorrow, 8:00 AM',
      pickup: '6:00 PM',
      center: 'Vetician Daycare, HSR Layout',
      activities: ['Supervised Play', 'Socialization', 'Naptime', 'Snacks'],
      caretaker: 'Meera Nair',
      emergencyContact: '+91 98765 43210',
    },
  },
  {
    id: '8',
    title: 'Pet Watch Service Started',
    description: "Coco's in-home watching session has started. Caretaker Ravi has checked in and sent you a photo update.",
    type: NOTIFICATION_TYPES.WATCHING,
    timestamp: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    isRead: false,
    petName: 'Coco',
    actionRoute: '/watching/live',
    extraDetails: {
      startTime: 'Today, 2:15 PM',
      endTime: 'Today, 8:00 PM',
      caretaker: 'Ravi Kumar',
      location: 'Your Home',
      updates: 'Photo update sent at 2:30 PM',
      contact: '+91 91234 56789',
    },
  },
];
